[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "hopfield-network"
version = "0.1.0"
description = "Hopfield network in Python with Hebbian and perceptron-like learning"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "matplotlib",
    "pillow",
    "numba",
    "scipy",
    "tqdm",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]